send_request: Search for proxy automatically if request fails. Log proxy_server used when dumping errors.

diff --git a/core/functions b/core/functions
--- a/core/functions
+++ b/core/functions
@@ -259,41 +259,52 @@ running_from_cron(){
 # if try_proxy does not contain a dot (e.g. 'true' or something else)
 # then lets make sure we use a valid proxy.
 get_proxy_server(){
-	[ -z "$try_proxy" ] && return 1
-
-	if [ -n "$(find_in $try_proxy '\.')" ]; then
-		echo "$try_proxy"
-	else
-		get_system_proxy
-	fi
-
+	[ -n "$try_proxy" ] && echo "$try_proxy" || get_system_proxy
 }
 
 send_request(){
 
 	local url="$1"
 	local curl_arguments="$2"
-	local proxy_server="$3"
+	local proxy_to_use="$3"
 
-	[ -n "$proxy_server" ] && curl_arguments="$curl_arguments -x $proxy_server"
+	if [ -n "$proxy_to_use" ]; then
+		log " -- Trying via proxy: ${proxy_to_use}..."
+		curl_arguments="$curl_arguments -x $proxy_to_use"
+	fi
+
 	local headers_file="$tmpbase/prey-curl-headers.txt"
-
 	response_body=$(getter $curl_arguments -L $url --dump-header "$headers_file" -S --stderr -)
+	local rs=$?
 
-	if [[ $? == 0 && -f "$headers_file" ]]; then
+	if [[ $rs -eq 0 && -f "$headers_file" ]]; then
 
 		response_headers=$(cat "$headers_file" && rm -f "$headers_file" 2> /dev/null)
 		get_status_code
 
-	elif [ -z "$proxy_server" ] && [ -n "$try_proxy" ]; then
+	elif [ -z "$proxy_to_use" ]; then
 
-		local proxy_to_use=$(get_proxy_server)
-		log " -- Unable to get response. Trying via proxy (${proxy_to_use})"
-		send_request "$url" "$curl_arguments" "$proxy_to_use"
+		if [ -z "$proxy_checked" ]; then
+			proxy_server=$(get_proxy_server)
+			proxy_checked=1
+		fi
 
-	else
+		if [ -n "$proxy_server" ]; then
+			send_request "$url" "$curl_arguments" "$proxy_server"
+		else
+			log_response_error "$url"
+		fi
 
-		log_response_error "$url"
+	else # tried proxy to no avail.
+
+		# it may be possible that the proxy does not support SSL,
+		# so we can try switching to plain HTTP as a last resort
+		if [ -n "$(find_in "$url" 'https:')" ]; then
+			local new_url=$(echo "$url" | sed 's/https:/http:/')
+			send_request "$new_url" "$curl_arguments" "$proxy_to_use"
+		else
+			log_response_error "$url" "$proxy_to_use"
+		fi
 
 	fi
 
@@ -316,9 +327,11 @@ get_last_response(){
 
 log_response_error(){
 	local url="$1"
-	log " !! Got invalid response! This probably means there is a connection issue."
+	local proxy_used="$2"
+	log "\n !! Got invalid response! This probably means there is a connection issue."
 	log " -- Please check your firewall settings, allowing Curl to connect to ${url} through port 80."
 	log " -- If you use a proxy server please check the try_proxy setting in the config file."
+	[ -n "$proxy_used" ] && log " -- Proxy server found: ${proxy_used}"
 	log " -- The response we got was: \n\n${response_headers}\n${response_body}\n"
 }
 
