moved hardware scan as a hook in system module

diff --git a/core/functions b/core/functions
--- a/core/functions
+++ b/core/functions
@@ -211,25 +211,24 @@ verify_installation(){
 # self setup functions
 ####################################################################
 self_setup(){
-	if [ -z $device_key ]; then
+	if [[ -n "$api_key" && -z "$device_key" ]]; then
 		
-		local post_url="$check_url/devices.xml"
 		local parms="device[title]=Mi Ubuntu&device[device_type]=Portable&device[os]=Linux&device[os_version]=Guadalinex"
-		if [ -d "$base_path/modules/system" ]; then
-		
-			initialize_module 'system'
-			add_job 'scan_hardware' 'system'
-		
-		fi
 		#echo -e "$parms"
-		response=`getter -u $api_key:x -i $post_url -d "$parms"`
+		response=`getter -u $api_key:x -i $check_url/devices.xml -d "$parms"`
 		#echo -e "$response"
 		status_code=`echo "$response" | grep "Status" | sed 's/.*:[[:space:]]\([[:digit:]]*\).*/\1/'`
-		if [ $status_code == "302" ]; then
-			echo " -- No more devices allowed for this account!"
-		else	
+		if [ $status_code == "201" ]; then
+
 			device_key=`echo "$response" | grep "<key>" | sed 's/.*<key>\(.*\)<\/key>.*/\1/'`
 			sed -i -e "s/device_key='.*'/device_key='$device_key'/" $base_path/config
+			echo " -- Device successfully added."
+
+		else	
+
+			echo -e " -- Couldn't add this device to your account. You probably don't have any slots left.\n"
+			exit 1
+
 		fi
 		
 		# exit 0
