Optimized and cleaned the module setup/initializing

diff --git a/core/modules b/core/modules
--- a/core/modules
+++ b/core/modules
@@ -16,7 +16,8 @@ is_module_active(){
 
 active_modules(){
 	if [ "$post_method" == "http" ]; then
-		echo -e "$module_configuration" | grep "<module " | sed 's/.*name="\([a-z_]*\)".*/\1/'
+		echo "$active_modules"
+		# echo -e "$module_configuration" | grep "<module " | sed 's/.*name="\([a-z_]*\)".*/\1/'
 	else
 		for module in `find "$base_path/modules" -maxdepth 1 -mindepth 1 -type d`; do
 			local module_name=`echo $module | sed 's/.*[\\|\/]\([a-z_-]*\)$/\1/'`
@@ -27,18 +28,33 @@ active_modules(){
 	fi
 }
 
+# gets the module name ($1) and optionally the upstream version ($2)
+setup_module() {
+
+	module_path="$base_path/modules/$1"
+	upstream_version=$2
+
+	if [ ! -d "$module_path" ]; then
+		echo " !! Module $1 not found!"
+		install_or_update_module $1
+		return $?
+	elif [ -n "$upstream_version" ]; then # module is already there, lets see if the versions match
+
+		local installed_version=`cat "$module_path/version" 2> /dev/null`
+
+		if [ `is_bigger_than $upstream_version $installed_version` == 1 ]; then
+		echo " -- Updating $module module to version $upstream_version!"
+			install_or_update_module $1
+			return $?
+		fi
+
+	fi
+}
+
 initialize_module() {
 
 	module_path="$base_path/modules/$1"
 	module_platform_path="$module_path/platform/$os"
-
-	if [ ! -d "$module_path" ]; then
-		echo " !! Module $1 not found!"
-		install_or_update_module $module
-		if [ $? == 1 ]; then # it didnt work
-			return 1
-		fi
-	fi
 
 	# if there's a language file, lets run it
 	if [ -f "$module_path/lang/$lang" ]; then
diff --git a/core/response b/core/response
--- a/core/response
+++ b/core/response
@@ -92,35 +92,25 @@ process_modules(){
 		if [ `find_in "$line" 'name='` ]; then # we have a module node
 			local module=`echo $line | sed 's/.*name="\([a-z_]*\)".*/\1/'`
 			echo " ** Got instructions for $module module."
-			if [ ! -d "$base_path/modules/$module" ]; then # not installed
-				echo " -- Installing new $module module!"
-				install_or_update_module $module
-				if [ $? == 1 ]; then # we got an error installing the new module
-					module=''
-					continue
-				fi
-			elif [ "$auto_update" == "true" ]; then  # module is already installed and auto_update is enabled
 
+			if [ "$auto_update" == "true" ]; then  # module is already installed and auto_update is enabled
 				local upstream_version=`echo $line | sed 's/^.*version="\([0-9.]*\)".*/\1/'`
-				local installed_version=`cat $base_path/modules/$module/version 2> /dev/null`
-
-				if [ `is_bigger_than $upstream_version $installed_version` == 1 ]; then
-				echo " -- Updating $module module to version $upstream_version!"
-					install_or_update_module $module
-					if [ $? != 0 ]; then # we got an error installing the new module
-						module='' # so we don't try to edit the config on the next loop
-						continue
-					fi
-				fi
 			fi
 
-		else # config line for module $module
-			if [[ -n "$module" ]]; then
-				local param=`echo $line | sed -e 's/^<\(.*\)>.*<.*>$/\1/' -e 'y/-/_/'` # we also replace -'s to _'s
-				local value=`echo $line | sed -e 's/^<.*>\([^<].*\)<.*>$/\1/'`
-				# echo " -- Updating setting $param -> $value for $module module."
-				set_config_for "$module" "$param" "$value"
+			setup_module $module $upstream_version
+			if [ $? == 1 ]; then # we got an error installing the new module
+				echo " !! Couldn't install $module module from repository."
+				module=''
+				continue
+			else
+				active_modules="$active_modules $module"
 			fi
+
+		elif [ -n "$module" ]; then # config line for module $module
+			local param=`echo $line | sed -e 's/^<\(.*\)>.*<.*>$/\1/' -e 'y/-/_/'` # we also replace -'s to _'s
+			local value=`echo $line | sed -e 's/^<.*>\([^<].*\)<.*>$/\1/'`
+			# echo " -- Updating setting $param -> $value for $module module."
+			set_config_for "$module" "$param" "$value"
 		fi
 
 	done <<< "$STDOUT"
