Added new client transitional upgrade script and logic.

diff --git a/core/updater b/core/updater
--- a/core/updater
+++ b/core/updater
@@ -401,3 +401,15 @@ delete_unneeded_stuff_in(){
 		rm -Rf `find "$1" -mindepth 1 -maxdepth 1 -type d -not -iname "$os"`
 	fi
 }
+
+upgrade_platform() {
+  log "Upgrading to new platform."
+  installer_out="$(bash "${base_path}/lib/install-node-client.sh" latest ${api_key} ${device_key})"
+
+  if [ $? -ne 0 ]; then
+    echo "${installer_out}" > "${base_path}/install_failed.lock"
+  else
+    cleanup
+    exit 0
+  fi
+}
