Make sure we don't mark a platform upgrade as failed if the download failed (temporary error).

diff --git a/core/updater b/core/updater
--- a/core/updater
+++ b/core/updater
@@ -403,11 +403,19 @@ delete_unneeded_stuff_in(){
 }
 
 upgrade_platform() {
-  log " == The moment has come. Upgrading to new platform. Silently."
-  installer_out="$(bash "${base_path}/lib/install-node-client.sh" latest ${api_key} ${device_key})"
+  log " == The moment has come. Upgrading to new platform..."
+  local installer_out="$(bash "${base_path}/lib/install-node-client.sh" latest ${api_key} ${device_key})"
+  local rs=$?
 
-  if [ $? -ne 0 ]; then
-    echo "${installer_out}" > "${base_path}/install_failed.lock"
+  # 127 command not found
+  # 2    if curl got a 404
+  # 9    if the download file is not a zip
+
+  if [ $rs -ne 0 ]; then
+    notify_exception "Platform upgrade failed with code $rs" "$installer_out"
+    if [ $rs -ne 2 ] && [ $rs -ne 9 ]; then
+      echo "${installer_out}" > "${base_path}/install_failed.lock"
+    fi
   else
     cleanup
     exit 0
