Fixed module updater. Added notification of failed updates

diff --git a/core/updater b/core/updater
--- a/core/updater
+++ b/core/updater
@@ -56,7 +56,7 @@ test_and_apply_diff() {
 	outcome=`$patcher --dry-run $patch_options`
 
 	if [ `find_in "$outcome" 'FAILED'` ]; then
-		# report_patch_error
+		report_patch_error
 		return 1
 	else
 		echo ' -- Everything smooth. Applying patch...'
@@ -69,7 +69,8 @@ test_and_apply_diff() {
 
 # this could be useful sometime in the future
 report_patch_error(){
-	$getter $somewhere -F patch[errors]=@$rejects_file
+	echo ' -- Notifying error back to your Control Panel account...'
+	$getter -X PUT -u $api_key:x $control_panel_url/devices/$device_key.xml -d "device[update_failed]=1" 2> /dev/null
 }
 
 delete_files_according_to_diff() {
@@ -173,7 +174,7 @@ update_prey() {
 
 get_module(){
 	rm "$module_file" 2> /dev/null
-	wget --user=$api_key --password=x "$modules_url/modules/get/$1" -O "$module_file" 2> /dev/null
+	$getter -u $api_key:x "$modules_url/modules/$1.zip" -o "$module_file" 2> /dev/null
 }
 
 install_or_update_module(){
@@ -189,17 +190,24 @@ install_or_update_module(){
 			rm -Rf "$base_path/modules/$1"
 		fi
 
+		echo ' -- Unzipping module...'
 		unzip "$module_file" -d "$base_path/modules" &> /dev/null
-		delete_unneeded_stuff_in "$base_path/modules/$1/platform"
 
-		rm "$module_file" 2> /dev/null
+		if [ $? == 0 ]; then
+			echo ' -- Cleaning up...'
+			delete_unneeded_stuff_in "$base_path/modules/$1/platform"
+			rm "$module_file" 2> /dev/null
 
-		echo " ** New $1 module placed and ready to go!"
-		return 0
+			echo " ** New $1 module placed and ready to go!"
+			return 0
+		fi
 	else
-		echo " !! Couldn't install $1 module from repository."
-		return 1
+		echo " -- Something went wrong while trying to fetch module from repository."
 	fi
+
+	echo " !! Couldn't get/install $1 module from repository."
+	return 1
+
 }
 
 delete_unneeded_stuff_in(){
