Fixed module downloader and config parser

diff --git a/platform/base b/platform/base
--- a/platform/base
+++ b/platform/base
@@ -136,7 +136,7 @@ function parse_headers {
 	# if its a zip file, unzip it in modules and run the active modules (the executable ones)
 	# if its a xml/json file, parse it and assign config values correspondingly
 function process_response {
-	if [ "$content_type" == "text/xml" ]; then
+	if [ "$content_type" == "application/xml" ]; then
 		echo ' -- Got XML. Parsing...'
 		response_type='xml'
 	elif [ "$content_type" == "application/octet-stream" ]; then
@@ -191,11 +191,12 @@ function process_xml {
 
 function process_config {
 
-	echo -e "$response" | sed -n '/<config>/,/<\/config>/p'  | grep -v "config>" | while read line; do
+	echo -e "$response" | sed -n '/<configuration>/,/<\/configuration>/p'  | grep -v "configuration>" | while read line; do
 
-		if [[ "$line" =~ 'delay="' ]]; then
+		if [[ "$line" =~ 'delay' ]]; then
 			delay=`echo $line | sed 's/^<.*>\([^<].*\)<.*>$/\1/'`
 			if [ -n "$delay" ]; then
+				echo " -- Setting delay to $delay minutes!"
 				(crontab -l | grep -v prey; echo "*/$delay * * * * $base_path/prey.sh > /dev/null") | crontab -
 			fi
 		fi
@@ -210,11 +211,15 @@ function process_modules {
 
 	if [[ "$line" =~ 'name="' ]]; then # we have a module node
 		module=`echo $line | sed 's/^<module name="\(.*\)" .*$/\1/g'`
-		# echo " -- Got instructions for $module module."
+		echo " -- Got instructions for $module module."
 		if [[ "$line" =~ "true" ]]; then # module is active
 			if [ ! -d $base_path/modules/$module ]; then
-				install_new_module $module # <-- we're only installing the module if it is active
 				echo " -- Installing new $module module..."
+				install_new_module $module # <-- we're only installing the module if it is active
+				if [ $? == 1 ]; then # error installing module
+					module=''
+					continue
+				fi
 			fi
 			if [ ! -x $base_path/modules/$module/run ]; then
 				echo " -- Enabling $module module!"
@@ -231,7 +236,7 @@ function process_modules {
 		if [[ -n "$module" && -f $base_path/modules/$module/config ]]; then # module is active and has configuration
 			param=`echo $line | sed 's/^<\(.*\)>.*<.*>$/\1/' | sed 'y/-/_/'` # we also replace -'s to _'s
 			value=`echo $line | sed 's/^<.*>\([^<].*\)<.*>$/\1/'`
-			# echo " -- Setting param $param -> $value for $module module."
+			echo " -- Updating setting $param -> $value for $module module."
 			sed -i -e "s/$param='.*'/$param='$value'/" $base_path/modules/$module/config
 		fi
 	fi
@@ -266,13 +271,17 @@ function process_zip {
 
 # this should work, we only need to set up the module repository!
 function install_new_module {
-	wget "$check_url/modules/download/$module?api_key=$api_key" -o /tmp/$1.zip &> /dev/null
-	if [ -f "/tmp/$1.zip" ]; then
-		echo " -- Got new module from $check_url! Unpackaging..."
+	wget "$check_url/modules/download/$module?api_key=$api_key" -O /tmp/$1.zip &> /dev/null
+	if [ `cat /tmp/$1.zip 2> /dev/null | wc -c` -gt 0 ]; then
+		echo " -- Got new module from repository! Unpackaging..."
 		mv /tmp/$1.zip $base_path/modules
 		unzip $base_path/modules/$1.zip
 		rm $base_path/modules/$1.zip
 		echo " -- New $1 module placed and ready to go!"
+		return 0
+	else
+		echo " !! Couldn't get $1 module from repository."
+		return 1
 	fi
 }
 
